name: Security Scanner

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    name: Scan Dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          pip install requests PyGithub
      
      - name: Run Security Scanner
        run: python scripts/security_scanner.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Security Report
        run: python scripts/create_report.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}